server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: BankApp

  datasource:
    url: jdbc:hsqldb:file:src/main/resources/db/test; hsqldb.lock_file=false;
    initialization-mode: always
    continue-on-error: true
    driver-class-name: org.hsqldb.jdbcDriver

  jpa:
    hibernate:
      ddl-auto: none